// Package genevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package genevents

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventType.
const (
	IoPlatformOrchestratorScopeSync EventType = "io.platform-orchestrator.scope.sync"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case IoPlatformOrchestratorScopeSync:
		return true
	default:
		return false
	}
}

// EventType defines model for EventType.
type EventType string

// OrgId defines model for OrgId.
type OrgId = string

// Scope The scope that needs to be synchronized.
type Scope = string

// ScopeSyncData defines model for ScopeSyncData.
type ScopeSyncData struct {
	OrgId OrgId `json:"org_id"`

	// Scope The scope that needs to be synchronized.
	Scope Scope `json:"scope"`
}

// UserId defines model for UserId.
type UserId = openapi_types.UUID
