// Package genevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package genevents

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventType.
const (
	IoPlatformOrchestratorScopeSync   EventType = "io.platform-orchestrator.scope.sync"
	IoPlatformOrchestratorSpicedbSync EventType = "io.platform-orchestrator.spicedb.sync"
)

// EventType defines model for EventType.
type EventType string

// OrgId defines model for OrgId.
type OrgId = string

// Scope The scope that needs to be synchronized.
type Scope = string

// ScopeSyncData defines model for ScopeSyncData.
type ScopeSyncData struct {
	OrgId OrgId `json:"org_id"`

	// Scope The scope that needs to be synchronized.
	Scope Scope `json:"scope"`
}

// SpiceDBSyncData defines model for SpiceDBSyncData.
type SpiceDBSyncData struct {
	OrgId  OrgId   `json:"org_id"`
	UserId *UserId `json:"user_id,omitempty"`
}

// UserId defines model for UserId.
type UserId = openapi_types.UUID
