package integrationtests

import (
	"net/http"
	"net/url"
	"testing"

	"github.com/google/uuid"
	"github.com/stellwerk-labs/platform-orchestrator-iam/internal/opt"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	serverclient "github.com/stellwerk-labs/platform-orchestrator-iam/shared/genclient"
)

// WorkOS Test Organization connection ID
const ssoOrganizationId = "org_01K80MD7R13WJPV61C5AZR9J3M"

func TestSsoInit(t *testing.T) {
	t.Parallel()

	orgId := "test-" + uuid.New().String()

	client, err := serverclient.NewClientWithResponses(mustServerURL(t), serverclient.WithHTTPClient(testHttpClient))
	require.NoError(t, err)

	internalClient, err := serverclient.NewClientWithResponses(mustInternalServerURL(t), serverclient.WithHTTPClient(testHttpClient))
	require.NoError(t, err)

	t.Run("configure sso for org", func(t *testing.T) {
		r, err := internalClient.InternalUpdateSsoConfigurationWithResponse(t.Context(), orgId, serverclient.InternalUpdateSsoConfigurationJSONRequestBody{ProviderOrgId: ssoOrganizationId})
		require.NoError(t, err)
		require.Equal(t, http.StatusOK, r.StatusCode(), "unexpected status %d", r.StatusCode())
	})

	var redirectUrl string
	t.Run("init sso flow", func(t *testing.T) {
		r, err := client.RequestSsoLoginWithResponse(t.Context(), serverclient.RequestSsoLoginJSONRequestBody{OrgId: orgId})
		require.NoError(t, err)
		if assert.Equal(t, http.StatusOK, r.StatusCode(), "unexpected status %d", r.StatusCode()) {
			redirectUrl = r.JSON200.RedirectUrl
			assert.Contains(t, redirectUrl, "https://api.workos.com/sso/authorize?")
		}
	})

	// It's hard to test WorkOS SSO with Test IdP, because the auth simulation is a part of admin console and is not
	// accessible via API token. So we test only failure cases. Success case can be added when we set our own test IdP.

	t.Run("callback with invalid code", func(t *testing.T) {
		// Extract the signed state from the redirect URL generated by the server
		parsedUrl, err := url.Parse(redirectUrl)
		require.NoError(t, err)
		state := parsedUrl.Query().Get("state")
		require.NotEmpty(t, state, "state should be present in redirect URL")

		r, err := client.GetSsoCallbackWithResponse(t.Context(), &serverclient.GetSsoCallbackParams{Code: opt.Of("INVALIDCODE").Ref(), State: &state})
		require.NoError(t, err)
		assert.Equal(t, http.StatusBadRequest, r.StatusCode(), "unexpected status %d", r.StatusCode())
	})

	t.Run("callback with error", func(t *testing.T) {
		r, err := client.GetSsoCallbackWithResponse(t.Context(), &serverclient.GetSsoCallbackParams{ErrorDescription: opt.Of("Unauthorized").Ref()})
		require.NoError(t, err)
		assert.Equal(t, http.StatusUnauthorized, r.StatusCode(), "unexpected status %d", r.StatusCode())
	})
}
